### PR TITLE
PR: new modern and minimal UI

### PR DESCRIPTION
**Pull request by Ashok-Kumar-dharanikota**
This PR refers to the #5 issue.

### CODE REVIEW

**Comment by SidharthMudgil** [comment]
Follow guidelines, provide before after ss

**Comment by Ashok-Kumar-dharanikota** [comment]
My Apologies to you @SidharthMudgil. 😅

As I already put the screenshots in the issue field. I thought repeating again wont be necessary. But that's not a issue. Here you can see the difference.

<table>
  <tr>
    <td>image</td>
    <td>Screenshot 2023-10-10 155209</td>
  </tr>
  <tr>
    <td>image</td>
    <td>Screenshot 2023-10-10 155356</td>
  </tr>
  <tr>
    <td>image</td>
    <td>Screenshot 2023-10-10 155528</td>
  </tr>
</table>

i saw this photo and was impressed by the filling background with red. Choosing Red as a primary color may give a great look I think. What would you say about it? (at first, as I am using the Jio network i won't able to see the image after VPN i saw this)

 
Screenshot 2023-10-20 203318

**Comment by SidharthMudgil** [comment]
the song card is better... but I didn't like the mine color scheme

the option part make something like this
image

also use modern vibrant colors

make search bar like this.. use simple material card with no background
image

make use of material3....

**Comment by Ashok-Kumar-dharanikota** [comment]
Okay sure! 😊👍

**Pull request closed without merging**
